# BÀI TẬP TIỀN XỬ LÝ DỮ LIỆU

**Họ và tên:** Phan Huy Hoàng
**MSSV:** 25410219

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("dataset_02.csv")

df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

### Xem 5 dòng đầu tiên

In [3]:
df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

### Xem kích thước bộ dữ liệu

In [4]:
df.shape

(205, 26)

### Xem kiểu dữ liệu của các cột

In [5]:
df.dtypes

symboling              int64
normalized-losses        str
make                     str
fuel-type                str
aspiration               str
num-of-doors             str
body-style               str
drive-wheels             str
engine-location          str
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type              str
num-of-cylinders         str
engine-size            int64
fuel-system              str
bore                     str
stroke                   str
compression-ratio    float64
horsepower               str
peak-rpm                 str
city-mpg               int64
highway-mpg            int64
price                    str
dtype: object

## 3. Xử lý giá trị bị khuyết

Trong bộ dữ liệu, giá trị bị khuyết được biểu diễn bằng dấu `?`.
Chuyển dấu `?` thành `NaN` để Pandas nhận diện được giá trị thiếu.

In [6]:
df.replace(
    to_replace="?",
    value=np.nan,
    inplace=True
)

df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

### Kiểm tra số lượng giá trị khuyết

In [7]:
df.isna().sum()

symboling             0
normalized-losses    41
make                  0
fuel-type             0
aspiration            0
num-of-doors          2
body-style            0
drive-wheels          0
engine-location       0
wheel-base            0
length                0
width                 0
height                0
curb-weight           0
engine-type           0
num-of-cylinders      0
engine-size           0
fuel-system           0
bore                  4
stroke                4
compression-ratio     0
horsepower            2
peak-rpm              2
city-mpg              0
highway-mpg           0
price                 4
dtype: int64

### 3.1. Xóa các dòng bị thiếu ở cột `price`

Sử dụng `dropna()` với `subset=["price"]` và `axis=0` để loại bỏ dòng.

In [8]:
df.dropna(
    subset=["price"],
    axis=0,
    inplace=True
)

df.shape

(201, 26)

### 3.2. Thay giá trị thiếu của `horsepower` bằng giá trị trung bình

Trước tiên chuyển cột `horsepower` sang kiểu `float`, sau đó tính mean.

In [9]:
df["horsepower"] = df["horsepower"].astype("float")

mean_horsepower = df["horsepower"].mean()

mean_horsepower

np.float64(103.39698492462311)

In [10]:
df["horsepower"] = df["horsepower"].replace(
    to_replace=np.nan,
    value=mean_horsepower
)

df["horsepower"].isna().sum()

np.int64(0)

### 3.3. Thay giá trị thiếu của `normalized-losses` bằng mode

Mode là giá trị xuất hiện nhiều nhất trong cột.

In [11]:
df["normalized-losses"] = df["normalized-losses"].astype("float")

mode_normalized_losses = df["normalized-losses"].mode()[0]

mode_normalized_losses

np.float64(161.0)

In [12]:
df["normalized-losses"] = df["normalized-losses"].replace(
    to_replace=np.nan,
    value=mode_normalized_losses
)

df["normalized-losses"].isna().sum()

np.int64(0)

### 3.4. Xóa các dòng vẫn còn giá trị bị khuyết

Sau khi xử lý các cột theo yêu cầu, loại bỏ các dòng vẫn còn `NaN`.

In [13]:
df.dropna(
    axis=0,
    inplace=True
)

df.shape

(193, 26)

In [14]:
df.isna().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
num-of-doors         0
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               0
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

## 4. Định dạng dữ liệu

Chuyển các cột đang có kiểu dữ liệu chưa phù hợp sang kiểu số bằng `astype()`.

In [15]:
df["normalized-losses"] = df["normalized-losses"].astype("int")
df["bore"] = df["bore"].astype("float")
df["stroke"] = df["stroke"].astype("float")
df["horsepower"] = df["horsepower"].astype("int")
df["peak-rpm"] = df["peak-rpm"].astype("int")
df["price"] = df["price"].astype("float")

df.dtypes

symboling              int64
normalized-losses      int64
make                     str
fuel-type                str
aspiration               str
num-of-doors             str
body-style               str
drive-wheels             str
engine-location          str
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type              str
num-of-cylinders         str
engine-size            int64
fuel-system              str
bore                 float64
stroke               float64
compression-ratio    float64
horsepower             int64
peak-rpm               int64
city-mpg               int64
highway-mpg            int64
price                float64
dtype: object

## 5. Chuyển giá trị số thành giá trị phân loại

Chia cột `price` thành ba nhóm:

- `Thấp`
- `Vừa`
- `Cao`

Dùng `np.linspace()` tạo 4 mốc để có 3 khoảng.

In [16]:
bins = np.linspace(
    min(df["price"]),
    max(df["price"]),
    4
)

bins

array([ 5118.        , 18545.33333333, 31972.66666667, 45400.        ])

In [17]:
group_names = ["Thấp", "Vừa", "Cao"]

df["price-bin"] = pd.cut(
    df["price"],
    bins,
    labels=group_names,
    include_lowest=True
)

df[["price", "price-bin"]].head(10)

      price price-bin
0   13495.0      Thấp
1   16500.0      Thấp
2   16500.0      Thấp
3   13950.0      Thấp
4   17450.0      Thấp
5   15250.0      Thấp
6   17710.0      Thấp
7   18920.0       Vừa
8   23875.0       Vừa
10  16430.0      Thấp

In [18]:
df["price-bin"].value_counts()

price-bin
Thấp    163
Vừa      18
Cao      12
Name: count, dtype: int64

## 6. Chuyển dữ liệu phân loại thành dữ liệu số

### 6.1. Integer Encoding cho cột `make`

Mỗi hãng xe được ánh xạ thành một số nguyên.

In [19]:
make_mapping = {
    "alfa-romero": 0,
    "audi": 1,
    "bmw": 2,
    "chevrolet": 3,
    "dodge": 4,
    "honda": 5,
    "isuzu": 6,
    "jaguar": 7,
    "mazda": 8,
    "mercedes-benz": 9,
    "mercury": 10,
    "mitsubishi": 11,
    "nissan": 12,
    "peugot": 13,
    "plymouth": 14,
    "porsche": 15,
    "renault": 16,
    "saab": 17,
    "subaru": 18,
    "toyota": 19,
    "volkswagen": 20,
    "volvo": 21
}

df["make"] = df["make"].map(make_mapping)

df[["make"]].head(10)

    make
0      0
1      0
2      0
3      1
4      1
5      1
6      1
7      1
8      1
10     2

### 6.2. Ordinal Encoding cho cột `num-of-doors`

Ánh xạ số cửa theo thứ tự:

- `two` thành `2`
- `four` thành `4`

In [20]:
door_mapping = {
    "two": 2,
    "four": 4
}

df["num-of-doors"] = df["num-of-doors"].map(door_mapping)

df["num-of-doors"].value_counts()

num-of-doors
4    112
2     81
Name: count, dtype: int64

### 6.3. One-hot Encoding cho các cột phân loại còn lại

Dùng `pd.get_dummies()` để chuyển mỗi giá trị phân loại thành các cột có giá trị `0` hoặc `1`.

Cột `price-bin` được giữ lại để quan sát kết quả phân nhóm giá.

In [21]:
categorical_columns = [
    "fuel-type",
    "aspiration",
    "body-style",
    "drive-wheels",
    "engine-location",
    "engine-type",
    "num-of-cylinders",
    "fuel-system"
]

df = pd.get_dummies(
    df,
    columns=categorical_columns,
    dtype=int
)

df.head()

,symboling,normalized-losses,make,num-of-doors,wheel-base,length,width,height,curb-weight,engine-size,...,num-of-cylinders_six,num-of-cylinders_three,num-of-cylinders_twelve,fuel-system_1bbl,fuel-system_2bbl,fuel-system_idi,fuel-system_mfi,fuel-system_mpfi,fuel-system_spdi,fuel-system_spfi
0,3,161,0,2,88.6,168.8,64.1,48.8,2548,130,...,0,0,0,0,0,0,0,1,0,0
1,3,161,0,2,88.6,168.8,64.1,48.8,2548,130,...,0,0,0,0,0,0,0,1,0,0
2,1,161,0,2,94.5,171.2,65.5,52.4,2823,152,...,1,0,0,0,0,0,0,1,0,0
3,2,164,1,4,99.8,176.6,66.2,54.3,2337,109,...,0,0,0,0,0,0,0,1,0,0
4,2,164,1,4,99.4,176.6,66.4,54.3,2824,136,...,0,0,0,0,0,0,0,1,0,0

In [22]:
df.shape

(193, 51)

## 7. Chuẩn hóa dữ liệu bằng phương pháp Z-score

Công thức:

\[
x_{new} = \frac{x_{old} - \mu}{\sigma}
\]

Chuẩn hóa các cột số ban đầu của bộ dữ liệu.
Không chuẩn hóa các cột vừa được mã hóa và các cột One-hot có giá trị `0`, `1`.

In [23]:
df["symboling"] = (
    df["symboling"] - df["symboling"].mean()
) / df["symboling"].std()

df["normalized-losses"] = (
    df["normalized-losses"] - df["normalized-losses"].mean()
) / df["normalized-losses"].std()

df["wheel-base"] = (
    df["wheel-base"] - df["wheel-base"].mean()
) / df["wheel-base"].std()

df["length"] = (
    df["length"] - df["length"].mean()
) / df["length"].std()

df["width"] = (
    df["width"] - df["width"].mean()
) / df["width"].std()

df["height"] = (
    df["height"] - df["height"].mean()
) / df["height"].std()

df["curb-weight"] = (
    df["curb-weight"] - df["curb-weight"].mean()
) / df["curb-weight"].std()

df["engine-size"] = (
    df["engine-size"] - df["engine-size"].mean()
) / df["engine-size"].std()

df["bore"] = (
    df["bore"] - df["bore"].mean()
) / df["bore"].std()

df["stroke"] = (
    df["stroke"] - df["stroke"].mean()
) / df["stroke"].std()

df["compression-ratio"] = (
    df["compression-ratio"] - df["compression-ratio"].mean()
) / df["compression-ratio"].std()

df["horsepower"] = (
    df["horsepower"] - df["horsepower"].mean()
) / df["horsepower"].std()

df["peak-rpm"] = (
    df["peak-rpm"] - df["peak-rpm"].mean()
) / df["peak-rpm"].std()

df["city-mpg"] = (
    df["city-mpg"] - df["city-mpg"].mean()
) / df["city-mpg"].std()

df["highway-mpg"] = (
    df["highway-mpg"] - df["highway-mpg"].mean()
) / df["highway-mpg"].std()

df["price"] = (
    df["price"] - df["price"].mean()
) / df["price"].std()

df.head()

,symboling,normalized-losses,make,num-of-doors,wheel-base,length,width,height,curb-weight,engine-size,...,num-of-cylinders_six,num-of-cylinders_three,num-of-cylinders_twelve,fuel-system_1bbl,fuel-system_2bbl,fuel-system_idi,fuel-system_mfi,fuel-system_mpfi,fuel-system_spdi,fuel-system_spfi
0,1.782215,0.918816,0,2,-1.678015,-0.442872,-0.839080,-2.117092,-0.025646,0.045098,...,0,0,0,0,0,0,0,1,0,0
1,1.782215,0.918816,0,2,-1.678015,-0.442872,-0.839080,-2.117092,-0.025646,0.045098,...,0,0,0,0,0,0,0,1,0,0
2,0.163544,0.918816,0,2,-0.719041,-0.250543,-0.184200,-0.613816,0.496473,0.574066,...,1,0,0,0,0,0,0,1,0,0
3,0.972880,1.002740,1,4,0.142410,0.182198,0.143240,0.179580,-0.426254,-0.459826,...,0,0,0,0,0,0,0,1,0,0
4,0.972880,1.002740,1,4,0.077395,0.182198,0.236794,0.179580,0.498371,0.189362,...,0,0,0,0,0,0,0,1,0,0

## 8. Kiểm tra kết quả sau khi xử lý

In [24]:
df.isna().sum()

symboling                  0
normalized-losses          0
make                       0
num-of-doors               0
wheel-base                 0
length                     0
width                      0
height                     0
curb-weight                0
engine-size                0
bore                       0
stroke                     0
compression-ratio          0
horsepower                 0
peak-rpm                   0
city-mpg                   0
highway-mpg                0
price                      0
price-bin                  0
fuel-type_diesel           0
fuel-type_gas              0
aspiration_std             0
aspiration_turbo           0
body-style_convertible     0
body-style_hardtop         0
body-style_hatchback       0
body-style_sedan           0
body-style_wagon           0
drive-wheels_4wd           0
drive-wheels_fwd           0
drive-wheels_rwd           0
engine-location_front      0
engine-location_rear       0
engine-type_dohc           0
engine-type_l              0
engine-type_ohc            0
engine-type_ohcf           0
engine-type_ohcv           0
num-of-cylinders_eight     0
num-of-cylinders_five      0
num-of-cylinders_four      0
num-of-cylinders_six       0
num-of-cylinders_three     0
num-of-cylinders_twelve    0
fuel-system_1bbl           0
fuel-system_2bbl           0
fuel-system_idi            0
fuel-system_mfi            0
fuel-system_mpfi           0
fuel-system_spdi           0
fuel-system_spfi           0
dtype: int64

In [25]:
df.dtypes

symboling                   float64
normalized-losses           float64
make                          int64
num-of-doors                  int64
wheel-base                  float64
length                      float64
width                       float64
height                      float64
curb-weight                 float64
engine-size                 float64
bore                        float64
stroke                      float64
compression-ratio           float64
horsepower                  float64
peak-rpm                    float64
city-mpg                    float64
highway-mpg                 float64
price                       float64
price-bin                  category
fuel-type_diesel              int64
fuel-type_gas                 int64
aspiration_std                int64
aspiration_turbo              int64
body-style_convertible        int64
body-style_hardtop            int64
body-style_hatchback          int64
body-style_sedan              int64
body-style_wagon              int64
drive-wheels_4wd              int64
drive-wheels_fwd              int64
drive-wheels_rwd              int64
engine-location_front         int64
engine-location_rear          int64
engine-type_dohc              int64
engine-type_l                 int64
engine-type_ohc               int64
engine-type_ohcf              int64
engine-type_ohcv              int64
num-of-cylinders_eight        int64
num-of-cylinders_five         int64
num-of-cylinders_four         int64
num-of-cylinders_six          int64
num-of-cylinders_three        int64
num-of-cylinders_twelve       int64
fuel-system_1bbl              int64
fuel-system_2bbl              int64
fuel-system_idi               int64
fuel-system_mfi               int64
fuel-system_mpfi              int64
fuel-system_spdi              int64
fuel-system_spfi              int64
dtype: object

In [26]:
df.shape

(193, 51)

In [27]:
df.head()

,symboling,normalized-losses,make,num-of-doors,wheel-base,length,width,height,curb-weight,engine-size,...,num-of-cylinders_six,num-of-cylinders_three,num-of-cylinders_twelve,fuel-system_1bbl,fuel-system_2bbl,fuel-system_idi,fuel-system_mfi,fuel-system_mpfi,fuel-system_spdi,fuel-system_spfi
0,1.782215,0.918816,0,2,-1.678015,-0.442872,-0.839080,-2.117092,-0.025646,0.045098,...,0,0,0,0,0,0,0,1,0,0
1,1.782215,0.918816,0,2,-1.678015,-0.442872,-0.839080,-2.117092,-0.025646,0.045098,...,0,0,0,0,0,0,0,1,0,0
2,0.163544,0.918816,0,2,-0.719041,-0.250543,-0.184200,-0.613816,0.496473,0.574066,...,1,0,0,0,0,0,0,1,0,0
3,0.972880,1.002740,1,4,0.142410,0.182198,0.143240,0.179580,-0.426254,-0.459826,...,0,0,0,0,0,0,0,1,0,0
4,0.972880,1.002740,1,4,0.077395,0.182198,0.236794,0.179580,0.498371,0.189362,...,0,0,0,0,0,0,0,1,0,0

## 9. Xuất bộ dữ liệu đã xử lý

In [28]:
df.to_csv(
    "dataset_02_processed.csv",
    index=False
)

print("Đã lưu file dataset_02_processed.csv")

Đã lưu file dataset_02_processed.csv