In [1]:
import pandas as pd
import numpy as np

In [ ]:
np.nan

In [8]:
df = pd.DataFrame(data={
    'A': [1, 2, np.nan, 4, 5],
    'B': [np.nan, 3, 4, 5, 6],
    'C': [5, 6, 7, 8, '?']
})

In [9]:
df

     A    B  C
0  1.0  NaN  5
1  2.0  3.0  6
2  NaN  4.0  7
3  4.0  5.0  8
4  5.0  6.0  ?

In [10]:
df.dropna()

     A    B  C
1  2.0  3.0  6
3  4.0  5.0  8
4  5.0  6.0  ?

In [11]:
df.dropna(axis=0, subset=['A'], inplace=True)

In [12]:
df.replace(to_replace='?', value=np.nan, inplace=True)

     A    B    C
0  1.0  NaN    5
1  2.0  3.0    6
3  4.0  5.0    8
4  5.0  6.0  NaN

In [13]:
df = pd.read_csv("data.csv")

In [19]:
headers = ["symboling",
           "normalized-losses",
           "make",
           "fuel-type",
           "aspiration",
           "num-of-doors",
           "body-style",
           "drive-wheels",
           "engine-location",
           "wheel-base",
           "length",
           "width",
           "height",
           "curb-weight",
           "engine-type",
           "num-of-cylinders",
           "engine-size",
           "fuel-system",
           "bore", "stroke",
           "compression-ratio",
           "horsepower",
           "peak-rpm",
           "city-mpg",
           "highway-mpg",
           "price"]

df = pd.read_csv("dataset_02.csv", names=headers)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
2,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
3,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
4,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
202,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
203,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
204,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
205,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [20]:
df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
2,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
3,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
4,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950

In [ ]:
df.replace(to_replace='?', value=np.nan, inplace=True)

In [21]:
df.dropna()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
2,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
3,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
4,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
202,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
203,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
204,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
205,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [22]:
s= pd.Series(data=[2, 5, 3, 6, 8])
s.mode()[0]

np.int64(2)

# Định dạng dữ liệu (Ví dụ thay thế giá trị)

Thay thế các giá trị chưa định dạng ở cột `Tam_tru` (`KTX`, `Ky tuc xa`, `Túc xá`, `Ký túc`) thành `Ký túc xá`.

In [23]:
import pandas as pd

df = pd.DataFrame({
    'Ren_luyen': [78, 87, 78, 98, 100, 99],
    'Tam_tru': ['KTX', 'Ky tuc xa', 'Túc xá', 'KTX', 'Ký túc xá', 'Ký túc'],
    'diem': [5.7, 8.6, 2.7, 8.5, 9.3, 7.5]
})

print("Dữ liệu ban đầu:")
print(df)

df_replaced = df.replace(to_replace={
    'Tam_tru': ['KTX', 'Ky tuc xa', 'Túc xá', 'Ký túc']
}, value='Ký túc xá')

print("\nDữ liệu sau khi định dạng (replace):")
print(df_replaced)

Dữ liệu ban đầu:
   Ren_luyen    Tam_tru  diem
0         78        KTX   5.7
1         87  Ky tuc xa   8.6
2         78     Túc xá   2.7
3         98        KTX   8.5
4        100  Ký túc xá   9.3
5         99     Ký túc   7.5

Dữ liệu sau khi định dạng (replace):
   Ren_luyen    Tam_tru  diem
0         78  Ký túc xá   5.7
1         87  Ký túc xá   8.6
2         78  Ký túc xá   2.7
3         98  Ký túc xá   8.5
4        100  Ký túc xá   9.3
5         99  Ký túc xá   7.5

In [23]:
df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
2,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
3,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
4,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950

In [27]:
df["city-mpg"].dtype

In [28]:
df["city-mpg"] = pd.to_numeric(df["city-mpg"], errors="coerce")
df["L/100km_city"] = 235 / df["city-mpg"]

In [ ]:
df

In [ ]:
# phương thức loại bỏ cột trong df

In [31]:
from sklearn.preprocessing import MinMaxScaler

In [32]:
mm = MinMaxScaler()

In [35]:
# công thức
df["length"] = (df["length"] - df["length"].min()) / (df["length"].max() - df["length"].min())
df

     length     width    height
0  0.000000  0.000000  0.000000
1  0.000000  0.000000  0.000000
2  0.100418  0.191781  0.521739
3  0.326360  0.287671  0.797101
4  0.326360  0.315068  0.797101
5  0.355649  0.301370  0.623188
6  1.000000  1.000000  1.000000

In [33]:
# thư viện
**mm.fit_transform(df[['length']])**

array([[0.        ],
       [0.        ],
       [0.10041841],
       [0.32635983],
       [0.32635983],
       [0.35564854],
       [1.        ]])